luajit: fix build issues, obey more vars
Rework how variables are passed in to ensure that more of our flag vars are
obeyed, make it obey more of our target path vars, and use fewer of its
hardcoded flags. Also add verbosity to the compile output for debugging.

Without this, errors were seen for us:

    | In file included from .../lib/gcc/i686-pc-linux-gnu/5.2.0/include-fixed/64/sgxx-glibc/syslimits.h:7:0,
    |                  from .../lib/gcc/i686-pc-linux-gnu/5.2.0/include-fixed/64/sgxx-glibc/limits.h:34,
    |                  from luaconf.h:12,
    |                  from lua.h:16,
    |                  from lj_arch.h:9:
    | .../lib/gcc/i686-pc-linux-gnu/5.2.0/include-fixed/64/sgxx-glibc/limits.h:168:61: fatal error: limits.h: No such file or directory
    | compilation terminated.
    | Makefile:233: *** Unsupported target architecture.  Stop.
    | make[1]: Leaving directory '.../luajit/2.0.4-r0/LuaJIT-2.0.4/src'

Signed-off-by: Christopher Larson <chris_larson@mentor.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 852cd67b916cdbe9f91d5323fe2a6cc790a7a0eb)
Signed-off-by: Armin Kuster <akuster808@gmail.com>